### ISSUE TITLE
XZ2 indexer should be lenient on coordinate values

### ISSUE THREAD

**Issue by vpipkt** [locationtech/rasterframes#531]
If the tile extent is beyond (-180.0, 180.0) latitude or (-90.0, 90.0) longitude the call to [GeoMesa XZ2SFC.index](https://github.com/locationtech/geomesa/blob/master/geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/XZ2SFC.scala#L42) will throw because we use [`lenient=false`](https://github.com/locationtech/rasterframes/blob/0.9.0/core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/XZ2Indexer.scala#L86).

Is there a compelling reason not to allow this index to extend beyond these bounds?

Background, originally reported here:

https://gitter.im/locationtech/geomesa?at=5fecdfc263fe0344962a53db 

https://geomesa.atlassian.net/browse/GEOMESA-2974

**Comment by duncanfwalker** [comment]
I'm not 100% sure whether flipping to lenient=true will completely fix the issue. 

By the looks of GeoMesa when we are lenient [it clamps the tile extent to the world extent](https://github.com/locationtech/geomesa/blob/a9e0e6910d11cb1b0827f7d27c4a993b3e586e24/geomesa-z3/src/main/scala/org/locationtech/geomesa/curve/XZ2SFC.scala#L336).

I think that means being lenient might result in duplicate indexes.  In the case where there are two different tiles that both go beyond the world extent they might the same index eg
Tiles with extents (90,91) and (91,92) get clamped to 90 is so get indexed as (90,90) and (90,90).

For the ERA5 use case that's fine because its just the edge tile that go slightly beyond 90 will get clamped so no risk of a duplicate.

**Comment by vpipkt** [comment]
@duncanfwalker  In my view the incorrect index value in this case should cause no logical errors in the users' programs. It remains to be seen if there is a real performance impact. 

It sounds like basically we agree that we should make this change. I'll put up a PR soon.
